#!/usr/bin/env python3
"""Generate src/bg.inc: 16 4bpp campus tiles (BG palette 1) and a 64x32 tilemap."""
import os, random
rng = random.Random(3)
# palette 1 (CGRAM 16-31)
RGB = [(0,0,0), (120,180,240), (245,245,255), (215,190,150), (170,145,110), (50,60,90), (255,230,120),
       (90,70,60), (110,70,40), (150,150,160), (120,120,130), (200,200,210), (60,140,70), (100,70,40),
       (25,25,30), (255,255,255)]
def T(s): return [[int(c, 16) for c in l] for l in s.split()]
TILES = [
 T("11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111"),   # 0 sky
 T("11111111 11122111 12222221 22222222 22222222 12222221 11122211 11111111"),   # 1 cloud
 T("33333333 33333433 33333333 34333333 33333333 33333343 33333333 33433333"),   # 2 wall
 T("44444444 45555554 45555554 45555554 45555554 45555554 45555554 44444444"),   # 3 window dark
 T("44444444 46666664 46666664 46666664 46666664 46666664 46666664 44444444"),   # 4 window lit
 T("77777777 77777777 33333333 33333333 33333333 33333333 33333333 33333333"),   # 5 roofline
 T("44444444 48888884 48888884 48888884 48888884 48888E84 48888884 48888884"),   # 6 door
 T("99999999 99999999 99999999 99999999 99999999 99999999 99999999 99999999"),   # 7 sidewalk
 T("BBBBBBBB BBBBBBBB AAAAAAAA 99999999 99999999 99999999 99999999 99999999"),   # 8 curb
 T("99999999 99999999 99999A99 9999A999 999A9999 99999999 99999999 99999999"),   # 9 crack
 T("AAAAAAAA 99999999 99999999 99999999 AAAAAAAA 99999999 99999999 99999999"),   # 10 paving
 T("11111111 111CC111 11CCCC11 1CCCCCC1 1CCCCCC1 11CCCC11 111DD111 111DD111"),   # 11 tree top
 T("111DD111 111DD111 111DD111 111DD111 111DD111 111DD111 111DD111 111DD111"),   # 12 trunk
 T("EEEEEEEE EFFFFFFE EF6FF6FE EFFFFFFE EF6F6FFE EFFFFFFE EEEEEEEE EEEEEEEE"),   # 13 sign
 T("11111111 11111111 11111111 11111111 11111111 11111111 77777777 33333333"),   # 14 roof top
 T("33333333 33333333 33333333 33333333 33333333 33333333 33333333 33333333"),   # 15 wall plain
]
W, Hh = 64, 32
m = [[0] * W for _ in range(Hh)]
for y in range(2, 6):
    for x in range(W):
        m[y][x] = 1 if rng.random() < 0.04 else 0
x = 0
while x < W:
    bw = rng.choice([5, 6, 7, 8])
    top = rng.choice([6, 7, 8, 9])
    for bx in range(x, min(W, x + bw)):
        m[top - 1][bx] = 14
        for y in range(top, 16):
            if y == top: m[y][bx] = 5
            elif (y - top) % 2 == 1 and bx - x in range(1, bw - 1) and (bx - x) % 2 == 1:
                m[y][bx] = 4 if rng.random() < 0.5 else 3
            else:
                m[y][bx] = 2 if rng.random() < 0.7 else 15
    if bw >= 6: m[15][x + bw // 2] = 6
    if x + bw < W and rng.random() < 0.5 and x + bw + 1 < W:
        m[14][x + bw] = 11; m[15][x + bw] = 12; x += 1
    x += bw
m[12][3] = 13
for x in range(W):
    m[16][x] = 8
    for y in range(17, Hh):
        r = rng.random()
        m[y][x] = 9 if r < 0.06 else (10 if r < 0.2 else 7)

def tile4bpp(t):
    out = bytearray()
    for pp in (0, 2):
        for y in range(8):
            b0 = b1 = 0
            for xx in range(8):
                v = t[y][xx]
                if v >> pp & 1: b0 |= 0x80 >> xx
                if v >> (pp + 1) & 1: b1 |= 0x80 >> xx
            out += bytes([b0, b1])
    return out
def bgr(c): r, g, b = (v >> 3 for v in c); return (b << 10) | (g << 5) | r
out = ['; generated by tools/bgmap.py', 'bg_tiles:']
for t in TILES: out.append('    .byte ' + ', '.join(f'${b:02X}' for b in tile4bpp(t)))
out.append('bg_pal:')
out.append('    .word ' + ', '.join(f'${bgr(c):04X}' for c in RGB))
out.append('bg_map:      ; 64x32 words, palette 1, SNES order: left 32x32 screen then right screen')
for scr in range(2):
    for y in range(Hh):
        out.append('    .word ' + ', '.join(f'${0x0400 | m[y][scr * 32 + xx]:04X}' for xx in range(32)))
here = os.path.dirname(os.path.abspath(__file__))
open(os.path.join(here, '..', 'src', 'bg.inc'), 'w').write('\n'.join(out) + '\n')
print('bg.inc written')
