#!/usr/bin/env python3
"""Generate src/tables.inc: sin table (1.0 = 32767), perspective reciprocals, cube model."""
import math, os
D = 160          # camera distance in pixels
S = 32 * 64      # cube half-size in pixels, 6 fractional bits
out = ['; generated by tools/gentables.py']
out.append('sin_tab:')
for i in range(256):
    out.append(f'    .word {round(math.sin(2 * math.pi * i / 256) * 32767) & 0xFFFF}')
out.append('recip_tab:   ; 16384 * D / (z + D) for z = -64..63')
for z in range(-64, 64):
    out.append(f'    .word {round(16384 * D / (z + D))}')
out.append('cube_verts:  ; x, y, z with 6 fractional bits')
for x in (-S, S):
    for y in (-S, S):
        for z in (-S, S):
            out.append(f'    .word {x & 0xFFFF}, {y & 0xFFFF}, {z & 0xFFFF}')
out.append('cube_edges:  ; vertex index pairs (bit0 = z, bit1 = y, bit2 = x)')
edges = [(a, b) for a in range(8) for b in range(a + 1, 8) if bin(a ^ b).count('1') == 1]
for a, b in edges:
    out.append(f'    .byte {a}, {b}')
assert len(edges) == 12
here = os.path.dirname(os.path.abspath(__file__))
open(os.path.join(here, '..', 'src', 'tables.inc'), 'w').write('\n'.join(out) + '\n')
print('tables.inc: 256 sin, 128 recip, 8 verts, 12 edges')
