#!/usr/bin/env python3
"""Navier-Stokes finite-time blowup (OpenAI 2026, arXiv-less PDF) visual model.

Reproduces the paper's Section 2/4 structure in the similarity variables it uses:
  tau = 1 - t,  A = 1/2 + h,  D = 1/2 - h,  0 < h < 1/100   (we take h = 1/128)
  X = r^2 / (2 tau),  eta = z / tau^D,  rho = sqrt(2X) = r / sqrt(tau)
  u_theta = tau^-A E(X,eta),  u_z = tau^-A U(X,eta),  r u_r = V0(X,eta)
Exact from the paper: the exponents, ell_r ~ tau^1/2, ell_z ~ tau^(1/2-h),
|u| ~ tau^(-1/2-h), core energy ~ tau^(1/2-3h), Re_theta ~ tau^-h, E = 0 on the
axis with E/sqrt(2X) smooth, E ~ c X^-A far out, inward spiral + axial outflow
split at z ~ 0 with a small upward bias, radial outflow farther out, pulse rings
in the annulus that grow on the shear and then decay viscously.
Stand-ins (the paper's profiles are solved numerically, not closed form):
  E = e0 sqrt(2X) / (1+2X)^(1+h)         -> Omega = e0 / (1+rho^2)^(1+h)
  U = u0 g(eta) exp(-X),  g = (eta + b) exp(-eta^2/2)
  V0 = -u0 g'(eta) (1 - exp(-X))          (from incompressibility)
Particles follow the flow in log-time s = -ln tau (self-similar dynamics):
  d rho/ds = rho/2 + V0/rho,  d eta/ds = D eta + U,  d theta/ds = tau^-h E/rho.
Generates src/ns_tables.inc for the ROM and a preview PNG when asked.
"""
import math, os, sys, random

H = 1 / 128
A, D = 0.5 + H, 0.5 - H
E0, U0, B = 9.0, 4.0, 0.15          # visual amplitudes; exponents are the paper's
DS = 1 / 32                          # log-time per GSU frame (15 fps)
FRAMES = 133                         # tau from 1 down to ~2^-6, then loop
RHO_CORE = 2.8                       # stagnation radius of the similarity flow
S_R, S_Z = 24.0, 30.0                # pixels per similarity unit at tau = 1 (256x192 screen)
TILT = math.radians(62)
NPART = 256
RING_N = 32
PULSE_LIFE = 32
PULSE_EVERY = 12
D0 = 320.0                           # camera distance in pixels for perspective
LIGHT = 0.15                         # light azimuth (turns) in view space
TUBE_RINGS, TUBE_SEGS = 14, 12

def omega(rho):            # turns per frame at tau = 1
    return E0 / (1 + rho * rho) ** (1 + H) * DS / (2 * math.pi)
def one_minus_exp_over_rho(rho):
    return (1 - math.exp(-rho * rho / 2)) / rho if rho > 1e-6 else rho / 2
def g(eta):  return (eta + B) * math.exp(-eta * eta / 2)
def gp(eta): return math.exp(-eta * eta / 2) * (1 - eta * (eta + B))
def amp(age):              # pulse envelope: growth on the shear, then viscous decay
    a = math.exp(0.32 * age) if age < 18 else math.exp(0.32 * 18) * math.exp(-0.44 * (age - 18))
    return 0.55 * a / math.exp(0.32 * 18)
def tube_eta(j): return -1.6 + 3.2 * j / (TUBE_RINGS - 1)
def tube_rho(eta): return 2.0 * math.sqrt(max(0.0, 1 - (eta / 1.75) ** 2)) + 0.15

def q15(x): return max(-32768, min(32767, int(round(x * 32768))))
def q14(x): return max(-32768, min(32767, int(round(x * 16384))))
def q12(x): return max(-32768, min(32767, int(round(x * 4096))))
def q11(x): return max(-32768, min(32767, int(round(x * 2048))))
def q10(x): return max(-32768, min(32767, int(round(x * 1024))))
def u16(x): return x & 0xFFFF

def frame_params(n):
    s = n * DS; tau = math.exp(-s)
    return dict(tau=tau, scale_r=math.sqrt(tau) * S_R, scale_z=tau ** D * S_Z,
                omf=tau ** -H, umax=tau ** -A, energy=tau ** (0.5 - 3 * H), re=tau ** -H,
                ell_r=math.sqrt(tau), ell_z=tau ** D)

def readout(n):
    p = frame_params(n)
    l1 = f"TAU {p['tau']:7.5f} LR {p['ell_r']:5.3f} LZ {p['ell_z']:5.3f}"
    l2 = f"UMAX X{p['umax']:5.2f} E X{p['energy']:5.3f} RE X{p['re']:5.3f}"
    return l1[:30].ljust(30), l2[:30].ljust(30)

def gen_tables(path):
    out = ['; generated by tools/nsmodel.py -- fixed-point tables for ns.gsu']
    out.append('ns_sin:      ; 256 x Q15')
    for i in range(256): out.append(f'    .word {u16(q15(math.sin(2*math.pi*i/256)))}')
    out.append('ns_atab:     ; u0*(1-e^-X)/rho*ds, Q15, rho = i/32')
    for i in range(256): out.append(f'    .word {u16(q15(U0 * one_minus_exp_over_rho(i/32) * DS))}')
    out.append('ns_btab:     ; u0*e^-X*ds, Q15, rho = i/32')
    for i in range(256): out.append(f'    .word {u16(q15(U0 * math.exp(-(i/32)**2/2) * DS))}')
    out.append('ns_gtab:     ; g(eta), Q14, eta = i/32 - 4')
    for i in range(256): out.append(f'    .word {u16(q14(g(i/32 - 4)))}')
    out.append('ns_gptab:    ; g\'(eta), Q14, eta = i/32 - 4')
    for i in range(256): out.append(f'    .word {u16(q14(gp(i/32 - 4)))}')
    out.append('ns_omtab:    ; Omega, Q16 turns/frame at tau=1, rho = i/32')
    for i in range(256): out.append(f'    .word {u16(int(round(omega(i/32) * 65536)))}')
    out.append('ns_amptab:   ; pulse amplitude by age, Q12 (similarity units)')
    for i in range(PULSE_LIFE): out.append(f'    .word {u16(q12(amp(i)))}')
    out.append('ns_recip2:   ; 16384*D0/(D0 + depth), depth = i-128 px, Q14')
    for i in range(256): out.append(f'    .word {u16(q14(D0 / (D0 + i - 128)))}')
    out.append('ns_recip8:   ; 128/dy for triangle edge slopes (Q7; dy=0,1 clamped)')
    for i in range(256): out.append(f'    .word {u16(min(127, int(round(128 / max(i, 2)))))}')
    out.append('ns_shade:    ; tube colour by view-space azimuth (2..9)')
    for i in range(256):
        c = math.cos(2 * math.pi * (i / 256 - LIGHT))
        out.append(f'    .byte {2 + int(round(3.5 + 3.5 * c))}')
    out.append('ns_tube:     ; ring eta Q12, ring rho Q12')
    for j in range(TUBE_RINGS):
        out.append(f'    .word {u16(q12(tube_eta(j)))}, {u16(q12(tube_rho(tube_eta(j))))}')
    out.append('ns_frames:   ; per frame: scale_r Q10, scale_z Q10, tau^-h Q14')
    for n in range(FRAMES):
        p = frame_params(n)
        out.append(f'    .word {u16(q10(p["scale_r"]))}, {u16(q10(p["scale_z"]))}, {u16(q14(p["omf"]))}')
    out.append('ns_text:     ; per frame: two 30-char readout lines')
    for n in range(FRAMES):
        l1, l2 = readout(n)
        out.append(f'    .byte "{l1}", "{l2}"')
    rng = random.Random(7)
    out.append('ns_particles: ; rho Q12, theta Q16, eta Q12')
    for _ in range(NPART):
        out.append(f'    .word {u16(q12(rng.uniform(0.2, 4.0)))}, {rng.randrange(65536)}, {u16(q12(rng.uniform(-2.0, 2.0)))}')
    out.append(f'NS_FRAMES = {FRAMES}')
    out.append(f'NS_NPART = {NPART}')
    open(path, 'w').write('\n'.join(out) + '\n')

# ---------------- reference simulation (float) for preview -----------------
class Sim:
    def __init__(self, seed=1):
        self.rng = random.Random(seed)
        self.p = [self.seed_particle() for _ in range(NPART)]
        self.pulses = []      # [rho_p, eta_p, sigma, theta0, phase, age]
        self.n = 0
    def seed_particle(self):
        r = self.rng
        return [r.uniform(0.2, 4.0), r.random(), r.uniform(-2.0, 2.0)]
    def step(self):
        omf = frame_params(self.n)['omf']
        for q in self.p:
            rho, th, eta = q
            drho = rho / 2 * DS - U0 * gp(eta) * one_minus_exp_over_rho(rho) * DS
            deta = D * eta * DS + U0 * g(eta) * math.exp(-rho * rho / 2) * DS
            th = (th + omega(rho) * omf) % 1.0
            rho += drho; eta += deta
            if rho >= 6 or abs(eta) >= 3 or rho < 0.02:
                q[:] = self.seed_particle()
            else:
                q[:] = [rho, th, eta]
        if self.n % PULSE_EVERY == 0:
            k = self.n // PULSE_EVERY
            fam = k & 1
            self.pulses.append([3.2 + 0.5 * fam, 0.7 if (k >> 1) & 1 else -0.7, 1 - 2 * fam, self.rng.random(), 0.0, 0])
        for pl in self.pulses:
            pl[3] = (pl[3] + omega(pl[0]) * omf) % 1.0
            pl[4] += 0.02
            pl[5] += 1
        self.pulses = [pl for pl in self.pulses if pl[5] < PULSE_LIFE]
        self.n = (self.n + 1) % FRAMES

    def project(self, rho, th, eta, fp):
        x = rho * math.cos(2 * math.pi * th) * fp['scale_r']
        y = rho * math.sin(2 * math.pi * th) * fp['scale_r']
        z = eta * fp['scale_z']
        sx = 64 + x
        sy = 64 - z * math.cos(TILT) + y * math.sin(TILT)
        return sx, sy

    def render(self):
        fp = frame_params(self.n)
        pts, lines = [], []
        # axis and core circle at z = 0
        pts += [(self.project(0, 0, e, fp), 2) for e in [i / 8 - 3 for i in range(49)]]
        ring = [self.project(RHO_CORE, i / 32, 0, fp) for i in range(33)]
        lines += [(ring[i], ring[i + 1], 2) for i in range(32)]
        for rho, th, eta in self.p:
            pts.append((self.project(rho, th, eta, fp), 3 if rho < RHO_CORE else 4))
        for rho_p, eta_p, sig, th0, ph, age in self.pulses:
            a = amp(age)
            r = []
            for i in range(RING_N + 1):
                t = th0 + i / RING_N
                w = math.sin(2 * math.pi * (6 * t) + ph)
                r.append(self.project(rho_p + a * w, t, eta_p + sig * 0.5 * a * math.cos(2 * math.pi * 6 * t + ph), fp))
            lines += [(r[i], r[i + 1], 5 if sig > 0 else 6) for i in range(RING_N)]
        return pts, lines

PAL = {0: (16, 8, 40), 1: (200, 200, 200), 2: (70, 70, 110), 3: (120, 255, 230),
       4: (70, 120, 200), 5: (255, 170, 60), 6: (240, 90, 220)}

def preview(path, frames=(0, 120, 240, 340)):
    from PIL import Image, ImageDraw
    sim = Sim()
    tiles = []
    last = 0
    for f in frames:
        while sim.n != f: sim.step()
        pts, lines = sim.render()
        im = Image.new('RGB', (128, 128), PAL[0]); d = ImageDraw.Draw(im)
        for (a, b, c) in lines: d.line([a, b], fill=PAL[c])
        for ((x, y), c) in pts:
            if 0 <= x < 128 and 0 <= y < 128: im.putpixel((int(x), int(y)), PAL[c])
        tiles.append(im.resize((384, 384), Image.NEAREST))
    sheet = Image.new('RGB', (384 * len(tiles), 384))
    for i, t in enumerate(tiles): sheet.paste(t, (384 * i, 0))
    sheet.save(path)

if __name__ == '__main__':
    here = os.path.dirname(os.path.abspath(__file__))
    gen_tables(os.path.join(here, '..', 'src', 'ns_tables.inc'))
    print('ns_tables.inc written')
    if len(sys.argv) > 1:
        preview(sys.argv[1]); print('preview', sys.argv[1])
