#!/usr/bin/env python3
"""Generate src/sprites.inc: a 128x128 4bpp sprite sheet (256 tiles) + palettes.
32x32 frames sit at sheet cells (col*4, row*4); OAM tile number = row*64 + col*4.
"""
import os

# ---------------- palettes (index 0 = transparent) ----------------
PLAYER_PAL = {'.': 0, 'k': 1, 'K': 2, 's': 3, 'S': 4, 'w': 5, 'g': 6, 'b': 7, 'B': 8, 'y': 9, 'o': 10, 'r': 11, 'G': 12}
PLAYER_RGB = [(0,0,0), (24,24,32), (56,56,72), (232,190,150), (190,140,100), (240,240,240), (90,90,110),
              (60,90,170), (35,55,120), (250,220,60), (250,150,50), (220,50,50), (140,140,160)]
NERD_PAL = {'.': 0, 'h': 1, 'p': 2, 'P': 3, 'w': 4, 'g': 5, 'r': 6, 'v': 7, 'V': 8, 'b': 9, 'B': 10, 'k': 11, 'y': 12}
NERD_RGB = [(0,0,0), (110,70,30), (240,200,170), (200,150,120), (245,245,245), (40,40,50), (210,40,60),
            (90,140,80), (60,100,55), (110,90,70), (70,55,40), (20,20,20), (250,230,120)]
ITEM_PAL = {'.': 0, 'w': 1, 'g': 2, 'k': 3, 'y': 4, 'o': 5, 'r': 6}
ITEM_RGB = [(0,0,0), (250,250,250), (170,170,190), (40,40,40), (255,240,80), (255,160,40), (240,60,60)]

def rows(s): return [l for l in s.strip('\n').split('\n')]

# ---------------- player: AI billionaire (hoodie, shades, phone) ----------------
P_HEAD = rows("""
................................
..........kkkkkkkkkk............
.........kkkkkkkkkkkk...........
........kkkkkkkkkkkkkk..........
........kkkssssssssskk..........
........kksssssssssskk..........
........kkgggggggggskk..........
........kkgGgggGgggskk..........
........kkssssssssSskk..........
.........ksssrrrsssk............
.........kSsssssssSk............
..........kkSSSSSkk.............
""")
P_TORSO = rows("""
..........kkkkkkkkkk............
........kkkkkkkkkkkkkk..........
.......kkkkkkkKkkkkkkkk.........
.......kkkkkkKKKkkkkkkk.........
.......kkkkkkkKkkkkkkkk.........
.......kkkkkkkkkkkkkkkk.........
.......kkk.kkkkkkkk.kkk.........
.......sss.kkkkkkkk.sss.........
.......sSs.kkkkkkkk.sSs.........
...........kkkkkkkk.............
...........kkyykkkk.............
...........kkkkkkkk.............
""")
P_TORSO_PUNCH = rows("""
..........kkkkkkkkkk............
........kkkkkkkkkkkkkk..........
.......kkkkkkkKkkkkkkkkkkkkkk...
.......kkkkkkKKKkkkkkkkkkkkkkkss
.......kkkkkkkKkkkkkkkkkkkkkksSs
.......kkkkkkkkkkkkkkkk.......ss
.......kkk.kkkkkkkk.............
.......sss.kkkkkkkk.............
.......sSs.kkkkkkkk.............
...........kkkkkkkk.............
...........kkyykkkk.............
...........kkkkkkkk.............
""")
P_LEGS = [rows("""
...........bbbbbbbb.............
...........bbbbbbbb.............
...........bbb..bbb.............
...........bbb..bbb.............
...........bbb..bbb.............
...........BBB..BBB.............
..........wwww..wwww............
..........GGGG..GGGG............
"""), rows("""
...........bbbbbbbb.............
..........bbbbbbbbbb............
.........bbb.....bbbb...........
........bbb.......bbb...........
.......bbb.........bbb..........
.......BBB.........BBB..........
......wwww.........wwww.........
......GGGG.........GGGG.........
"""), rows("""
...........bbbbbbbb.............
...........bbbbbbbb.............
...........bbbbbbbb.............
...........bbbbbbbb.............
...........bbb..bbb.............
...........BBB..BBB.............
..........wwww..wwww............
..........GGGG..GGGG............
""")]

# ---------------- nerd: glasses, bow tie, vest, papers ----------------
N_HEAD = rows("""
................................
..........hhhhhhhhhh............
.........hhhhhhhhhhhh...........
.........hhhhhhhhhhhh...........
.........hhpppppppphh...........
.........hppppppppppp...........
.........gggggggggggg...........
.........gwwgpppgwwgp...........
.........ggggpppgggg............
..........ppppPppppp............
..........pPppppppPp............
...........ppPPPPPpp............
""")
N_TORSO = rows("""
...........wwrrrrww.............
.........wwwwrrrrwwww...........
........wvvvvwwwwvvvvw..........
........wvvvvvvvvvvvvw..........
........wvvvvVvvvvvvvw..........
........wvvvvvvvvvvvvw..........
........ww.vvvvvvvv.ww..........
........pp.vvvvvvvv.pp..........
........pp.vvvvvvvv.pp..........
...........vvvvvvvv.............
...........vvvvvvvv.............
...........vvvvvvvv.............
""")
N_TORSO_PUNCH = rows("""
...........wwrrrrww.............
.........wwwwrrrrwwww...........
........wvvvvwwwwvvvvwwwwwwww...
........wvvvvvvvvvvvvwwwwwwwwppp
........wvvvvVvvvvvvvwwwwwwwwppp
........wvvvvvvvvvvvvw.......pp.
........ww.vvvvvvvv.............
........pp.vvvvvvvv.............
........pp.vvvvvvvv.............
...........vvvvvvvv.............
...........vvvvvvvv.............
...........vvvvvvvv.............
""")
N_LEGS = [rows("""
...........bbbbbbbb.............
...........bbbbbbbb.............
...........bbb..bbb.............
...........bbb..bbb.............
...........bbb..bbb.............
...........BBB..BBB.............
..........kkkk..kkkk............
..........kkkk..kkkk............
"""), rows("""
...........bbbbbbbb.............
..........bbbbbbbbbb............
.........bbb.....bbbb...........
........bbb.......bbb...........
.......bbb.........bbb..........
.......BBB.........BBB..........
......kkkk.........kkkk.........
......kkkk.........kkkk.........
"""), rows("""
...........bbbbbbbb.............
...........bbbbbbbb.............
...........bbbbbbbb.............
...........bbbbbbbb.............
...........bbb..bbb.............
...........BBB..BBB.............
..........kkkk..kkkk............
..........kkkk..kkkk............
""")]
N_HIT = rows("""
................................
................................
.....y....hhhhhhhhhh....y.......
......y..hhhhhhhhhhhh..y........
.........hhhhhhhhhhhh...........
.........hhpppppppphh...........
.........hppppppppppp...........
.........gggggggggggg...........
.........gwgggpppgwgg.p.........
.........ggggpppgggg............
..........ppppPppppp............
..........pPpppppPpp............
...........ppPPPPPpp............
...........wwrrrrww.............
.........wwwwrrrrwwww...........
........wvvvvwwwwvvvvw..........
.......pwvvvvvvvvvvvvwp.........
.......pwvvvvVvvvvvvvwp.........
........wvvvvvvvvvvvvw..........
........w..vvvvvvvv..w..........
...........vvvvvvvv.............
...........vvvvvvvv.............
..........bbbbbbbbbb............
.........bbbbbbbbbbbb...........
........bbbb......bbbb..........
.......bbbb........bbbb.........
......bbb............bbb........
......BBB............BBB........
.....kkkk............kkkk.......
.....kkkk............kkkk.......
................................
................................
""")
PAPER = rows("""
....wwwwwwwwww..
....wwwwwwwwww..
....wgggggggww..
....wwwwwwwwww..
....wggggggwww..
....wwwwwwwwww..
....wgggggggww..
....wwwwwwwwww..
....wggggwwwww..
....wwwwwwwwww..
....wgggggggww..
....wwwwwwwwww..
....wggggggwww..
....wwwwwwwwww..
....wwwwwwwwww..
................
""")
STAR = rows("""
................
.......y........
......yyy.......
.......y........
..y....y....y...
...y..yoy..y....
....yyoooyy.....
.....yorooy.....
.yyyyyoroyyyyy..
.....yorooy.....
....yyoooyy.....
...y..yoy..y....
..y....y....y...
.......y........
......yyy.......
.......y........
""")

def frame(head, torso, legs): return head + torso + legs

FRAMES = [  # (row, col, art, palette)
    (0, 0, frame(P_HEAD, P_TORSO, P_LEGS[0]), PLAYER_PAL),
    (0, 1, frame(P_HEAD, P_TORSO, P_LEGS[1]), PLAYER_PAL),
    (0, 2, frame(P_HEAD, P_TORSO, P_LEGS[2]), PLAYER_PAL),
    (0, 3, frame(P_HEAD, P_TORSO_PUNCH, P_LEGS[0]), PLAYER_PAL),
    (1, 0, frame(N_HEAD, N_TORSO, N_LEGS[0]), NERD_PAL),
    (1, 1, frame(N_HEAD, N_TORSO, N_LEGS[1]), NERD_PAL),
    (1, 2, frame(N_HEAD, N_TORSO, N_LEGS[2]), NERD_PAL),
    (1, 3, frame(N_HEAD, N_TORSO_PUNCH, N_LEGS[0]), NERD_PAL),
    (2, 0, N_HIT, NERD_PAL),
]
SMALL = [  # 16x16 at (row, col) in 16x16-cell units of sheet row 2 (cells 8+)
    (2, 8, PAPER, ITEM_PAL),
    (2, 10, STAR, ITEM_PAL),
]

def blit(sheet, art, pal, x0, y0):
    for y, line in enumerate(art):
        for x, ch in enumerate(line):
            sheet[y0 + y][x0 + x] = pal[ch]

def tile4bpp(sheet, tx, ty):
    out = bytearray()
    for plane_pair in (0, 2):
        for y in range(8):
            b0 = b1 = 0
            for x in range(8):
                v = sheet[ty * 8 + y][tx * 8 + x]
                if v >> plane_pair & 1: b0 |= 0x80 >> x
                if v >> (plane_pair + 1) & 1: b1 |= 0x80 >> x
            out += bytes([b0, b1])
    return out

def bgr(rgb): r, g, b = (c >> 3 for c in rgb); return (b << 10) | (g << 5) | r

def main():
    sheet = [[0] * 128 for _ in range(128)]
    for row, col, art, pal in FRAMES:
        assert len(art) == 32 and all(len(l) == 32 for l in art), (row, col)
        blit(sheet, art, pal, col * 32, row * 32)
    for row, cell, art, pal in SMALL:
        assert len(art) == 16 and all(len(l) == 16 for l in art)
        blit(sheet, art, pal, cell * 8, row * 32)
    out = ['; generated by tools/sprites.py -- 256 4bpp tiles, sheet order']
    out.append('sprite_tiles:')
    for ty in range(16):
        for tx in range(16):
            t = tile4bpp(sheet, tx, ty)
            out.append('    .byte ' + ', '.join(f'${b:02X}' for b in t))
    out.append('sprite_tiles_end:')
    out.append('sprite_pals:  ; 3 x 16 colours BGR555 (player, nerd, items)')
    for rgbs in (PLAYER_RGB, NERD_RGB, ITEM_RGB):
        vals = [bgr(c) for c in rgbs] + [0] * (16 - len(rgbs))
        out.append('    .word ' + ', '.join(f'${v:04X}' for v in vals))
    here = os.path.dirname(os.path.abspath(__file__))
    open(os.path.join(here, '..', 'src', 'sprites.inc'), 'w').write('\n'.join(out) + '\n')
    try:
        from PIL import Image
        im = Image.new('RGB', (128, 128), (255, 0, 255))
        pals = {id(PLAYER_PAL): PLAYER_RGB, id(NERD_PAL): NERD_RGB, id(ITEM_PAL): ITEM_RGB}
        for row, col, art, pal in FRAMES:
            for y, l in enumerate(art):
                for x, ch in enumerate(l):
                    if pal[ch]: im.putpixel((col * 32 + x, row * 32 + y), pals[id(pal)][pal[ch]])
        for row, cell, art, pal in SMALL:
            for y, l in enumerate(art):
                for x, ch in enumerate(l):
                    if pal[ch]: im.putpixel((cell * 8 + x, row * 32 + y), pals[id(pal)][pal[ch]])
        p = os.environ.get('SHEET_PNG')
        if p: im.resize((512, 512), Image.NEAREST).save(p)
    except ImportError:
        pass
    print('sprites.inc written')

if __name__ == '__main__':
    main()
